openapi: 3.0.3
info:
  version: 1.0.0
  title: WLED JSON API
  description: |
    OpenAPI specification for the WLED JSON API, providing control and monitoring of WLED devices.
    
    This API allows you to interact with WLED devices to control LED effects, colors, and device settings.
  contact:
    name: WLED Project
    url: https://github.com/Aircoookie/WLED
  license:
    name: MIT License
    url: https://github.com/Aircoookie/WLED/blob/master/LICENSE

servers:
  - url: http://{device}
    description: WLED device
    variables:
      device:
        default: wled.local
        description: The hostname or IP address of your WLED device

paths:
  /json/info:
    $ref: 'paths/json_info.yaml'
  /json/state:
    $ref: 'paths/json_state.yaml'
  /json/cfg:
    $ref: 'paths/json_cfg.yaml'

components:
  schemas:
    DeviceInfo:
      $ref: 'components/schemas/DeviceInfo.yaml'
    VersionInfo:
      $ref: 'components/schemas/VersionInfo.yaml'
    HardwareInfo:
      $ref: 'components/schemas/HardwareInfo.yaml'
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic 