openapi: 3.0.3
info:
  title: WLED JSON API
  version: '0.14'
  description: |
    JSON API for controlling WLED LED controllers.
    This API allows you to control LED effects, colors, and device settings.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://wled.local
    description: Local WLED device

tags:
  - name: State
    description: LED state control
  - name: Config
    description: Device configuration
  - name: Info
    description: Device information
  - name: Effects
    description: LED effects management
  - name: Palettes
    description: Color palette management

paths:
  /json/state:
    $ref: paths/json_state.yaml
  /json/cfg:
    $ref: paths/json_cfg.yaml
  /json/info:
    $ref: paths/json_info.yaml
  /json/eff:
    $ref: paths/json_eff.yaml
  /json/pal:
    $ref: paths/json_pal.yaml

components:
  schemas:
    DeviceInfo:
      $ref: components/schemas/DeviceInfo.yaml
    Effects:
      $ref: components/schemas/Effects.yaml
    Effect:
      $ref: components/schemas/Effect.yaml
    Palettes:
      $ref: components/schemas/Palettes.yaml
    Palette:
      $ref: components/schemas/Palette.yaml
  responses:
    UnauthorizedError:
      $ref: components/responses/UnauthorizedError.yaml
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: [] 