openapi: 3.0.3
info:
  title: WLED JSON API
  version: '0.14'
  description: |
    JSON API for controlling WLED LED controllers.
    This API allows you to control LED effects, colors, and device settings.

    # Introduction
    WLED is a fast and feature-rich implementation of an ESP8266/ESP32 webserver to control NeoPixel (WS2812B, WS2811, SK6812) LEDs or also SPI based chipsets like the WS2801 and APA102.

    # Authentication
    Basic authentication can be enabled in WLED settings. When enabled, all API endpoints require basic auth.

  termsOfService: 'https://github.com/Aircoookie/WLED/blob/master/LICENSE'
  contact:
    name: WLED Project
    url: 'https://github.com/Aircoookie/WLED'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  x-logo:
    url: 'https://raw.githubusercontent.com/Aircoookie/WLED/master/images/wled_logo_akemi.png'
    altText: WLED Logo

externalDocs:
  description: WLED Wiki and Documentation
  url: 'https://kno.wled.ge/'

servers:
  - url: http://wled.local
    description: Local WLED device (mDNS)
  - url: http://{ip}
    description: WLED device by IP address
    variables:
      ip:
        default: '192.168.1.4'
        description: IP address of your WLED device

tags:
  - name: State Management
    description: LED state control (brightness, effects, segments)
  - name: Configuration Management
    description: Device configuration and settings
  - name: Device Information
    description: Device information and capabilities
  - name: Effects and Palettes
    description: LED effects and color palette management
  - name: Network
    description: Network discovery and configuration
    externalDocs:
      description: Network Features Documentation
      url: './docs/network_features.md'
  - name: Live Data
    description: Real-time LED control (experimental)
    externalDocs:
      description: Live Data Documentation
      url: './docs/live_data.md'

paths:
  /json/state:
    $ref: paths/json_state.yaml
  /json/si:
    $ref: paths/json_si.yaml
  /json/cfg:
    $ref: paths/json_cfg.yaml
  /json/info:
    $ref: paths/json_info.yaml
  /json/eff:
    $ref: paths/json_eff.yaml
  /json/fxda:
    $ref: paths/json_fxda.yaml
  /json/pal:
    $ref: paths/json_pal.yaml
  /json/nodes:
    $ref: paths/json_nodes.yaml
  /json/net:
    $ref: paths/json_net.yaml
  /json/live:
    $ref: paths/json_live.yaml

components:
  schemas:
    DeviceInfo:
      $ref: components/schemas/DeviceInfo.yaml
    StateInfoResponse:
      $ref: components/schemas/StateInfoResponse.yaml
    Effects:
      $ref: components/schemas/Effects.yaml
    Effect:
      $ref: components/schemas/Effect.yaml
    EffectDataResponse:
      $ref: components/schemas/EffectDataResponse.yaml
    Palettes:
      $ref: components/schemas/Palettes.yaml
    Palette:
      $ref: components/schemas/Palette.yaml
    Node:
      $ref: components/schemas/Node.yaml
    Nodes:
      $ref: components/schemas/Nodes.yaml
    Network:
      $ref: components/schemas/Network.yaml
    NetworkList:
      $ref: components/schemas/NetworkList.yaml
    Live:
      $ref: components/schemas/Live.yaml
  responses:
    BadRequest:
      $ref: components/responses/BadRequest.yaml
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic authentication when enabled in WLED settings

security:
  - basicAuth: [] 