description: Information about the access point that the ESP hosts when enabled, or when connecting to other AP fails
type: object
properties:
  ssid:
    type: string
    description: SSID of local AP
    nullable: true
  pskl:
    type: integer
    description: Length of AP password (password is wled1234 by default)
    minimum: 0
    nullable: true
  chan:
    type: integer
    format: uint8
    description: 2.4GHz WiFi AP channel (1-13)
    minimum: 1
    maximum: 13
    nullable: true
  hide:
    type: integer
    format: uint8
    description: Hidden AP SSID flag (0 = visible, 1 = hidden)
    minimum: 0
    maximum: 255
    nullable: true
  behav:
    type: integer
    format: uint8
    description: |
      Access point behavior mode:
      * 0 = Open AP when no connection after boot
      * 1 = Open when no connection (either after boot or if connection is lost)
      * 2 = Always open
      * 3 = Only when button pressed for 6 sec
      * 4-9 = Reserved for future use
    enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    nullable: true
    x-enumNames:
      - ApBehaviorBootNoConn
      - ApBehaviorNoConn
      - ApBehaviorAlways
      - ApBehaviorButtonOnly
      - RSVD1
      - RSVD2
      - RSVD3
      - RSVD4
      - RSVD5
      - RSVD6
  ip:
    type: array
    description: IP to host the website when on AP (default 4.3.2.1)
    items:
      type: integer
      format: uint8
      minimum: 0
      maximum: 255
    minItems: 4
    maxItems: 4
    nullable: true
required: []
example:
  ssid: "WLED-AP"
  pskl: 8
  chan: 1
  hide: 0
  behav: 0
  ip: [4, 3, 2, 1] 