type: object
description: Color order mapping for LED segments
properties:
  start:
    type: integer
    format: uint16
    description: Start index
  len:
    type: integer
    format: uint16
    description: Length
  order:
    type: integer
    format: uint8
    description: Color order
example:
  start: 0
  len: 144
  order: 0 