description: Ethernet configuration settings
type: object
properties:
  relay:
    type: integer
    format: uint8
    description: |
      Type of ethernet board/module.
      - `0`: WledEthNone
      - `1`: WledEthWt32Eth01
      - `2`: WledEthEsp32Poe
      - `3`: WledEthWesp32
      - `4`: WledEthQuinled
      - `5`: WledEthTwilightlord
      - `6`: WledEthEsp32deux
      - `7`: WledEthEsp32ethkitve
      - `8`: WledEthQuinledOcta
      - `9`: WledEthAbcwledv43eth
      - `10`: WledEthSerg74
      - `11`-`18`: Reserved
    enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
    nullable: true
    x-enumNames:
      - WledEthNone
      - WledEthWt32Eth01
      - WledEthEsp32Poe
      - WledEthWesp32
      - WledEthQuinled
      - WledEthTwilightlord
      - WledEthEsp32deux
      - WledEthEsp32ethkitve
      - WledEthQuinledOcta
      - WledEthAbcwledv43eth
      - WledEthSerg74
      - RSVD1
      - RSVD2
      - RSVD3
      - RSVD4
      - RSVD5
      - RSVD6
      - RSVD7
      - RSVD8
  pin:
    type: array
    description: Pin configuration for the ethernet module
    items:
      type: integer
      format: uint32
      minimum: 0
      maximum: 4294967295
    nullable: true
required: []
example:
  relay: 1
  pin: [1, 2, 3, 4] 