description: Hardware configuration settings
type: object
properties:
  led:
    $ref: './LedConfig.yaml'
  com:
    type: array
    description: List of color order maps
    nullable: true
    items:
      $ref: './ColorOrderMap.yaml'
  btn:
    $ref: './ButtonConfig.yaml'
  ir:
    $ref: './InfraredConfig.yaml'
  relay:
    $ref: './RelayConfig.yaml'
  baud:
    type: integer
    format: uint16
    description: Baud rate divided by 100
    minimum: 0
    maximum: 65535
    nullable: true
  if:
    type: object
    description: Interface configuration
    nullable: true
    properties:
      i2c-pin:
        type: array
        description: I2C pins [SDA, SCL]
        minItems: 2
        maxItems: 2
        items:
          type: integer
          format: int8
          minimum: -128
          maximum: 127
        nullable: true
      spi-pin:
        type: array
        description: SPI pins [MOSI, SCLK, MISO]
        minItems: 3
        maxItems: 3
        items:
          type: integer
          format: int8
          minimum: -128
          maximum: 127
        nullable: true
required: []
example:
  led:
    total: 30
    maxpwr: 850
    ledma: 0
    cct: false
    cr: false
    ic: false
    cb: 0
    fps: 42
    rgbwm: 255
    ld: true
    ins:
      - start: 0
        len: 30
        pin: [16]
        order: 0
        rev: false
        skip: 0
        type: 22
        ref: false
        rgbwm: 0
        freq: 0
        maxpwr: 850
        ledma: 55
  com: []
  btn:
    max: 4
    pull: true
    tt: 32
    mqtt: false
    ins:
      - type: 2
        pin: [0]
        macros: [0, 0, 0]
      - type: 0
        pin: [-1]
        macros: [0, 0, 0]
      - type: 0
        pin: [0]
        macros: [0, 0, 0]
      - type: 0
        pin: [0]
        macros: [0, 0, 0]
  ir:
    pin: -1
    type: 0
    sel: true
  relay:
    pin: -1
    rev: false
    odrain: false
  baud: 1152
  if:
    i2c-pin: [-1, -1]
    spi-pin: [-1, -1, -1] 