description: Hardware configuration settings
type: object
properties:
  led:
    $ref: './LedConfig.yaml'
  com:
    type: array
    description: List of color order maps
    nullable: true
    items:
      $ref: './ColorOrderMap.yaml'
  btn:
    $ref: './ButtonConfig.yaml'
  ir:
    $ref: './InfraredConfig.yaml'
  relay:
    $ref: './RelayConfig.yaml'
  baud:
    type: integer
    format: uint16
    description: Baud rate divided by 100
    minimum: 0
    maximum: 65535
    nullable: true
  if:
    type: object
    description: Interface configuration
    nullable: true
    properties:
      i2c-pin:
        type: array
        description: I2C pins [SDA, SCL]
        minItems: 2
        maxItems: 2
        items:
          type: integer
          format: int8
          minimum: -128
          maximum: 127
        nullable: true
      spi-pin:
        type: array
        description: SPI pins [MOSI, SCLK, MISO]
        minItems: 3
        maxItems: 3
        items:
          type: integer
          format: int8
          minimum: -128
          maximum: 127
        nullable: true
required: []
example:
  led:
    total: 100
    maxpwr: 1000
    ledma: 50
    cct: false
    cr: false
    cb: 0
    fps: 60
    rgbwm: 255
    ld: false
    matrix:
      mpc: 1
      panels:
        - b: false
          r: false
          v: false
          s: true
          x: 0
          y: 0
          h: 16
          w: 16
    ins:
      - start: 0
        len: 100
        pin: [2]
        order: 0
        rev: false
        skip: 0
        type: 22
        ref: false
        rgbwm: 0
        freq: 800
  com:
    - start: 0
      len: 100
      order: 0
  btn:
    max: 4
    pull: true
    tt: 32
    mqtt: false
    ins:
      - type: 2
        pin: [0]
        macros:
          "0": 1
          "1": 2
          "2": 3
  ir:
    pin: 4
    type: 1
    sel: true
  relay:
    pin: 5
    rev: false
  baud: 96
  if:
    i2c-pin: [21, 22]
    spi-pin: [23, 18, 19] 