type: object
description: Infrared receiver configuration
properties:
  pin:
    type: integer
    description: IR receiver pin
  type:
    type: integer
    description: IR receiver type
example: {} 