description: Interface configuration settings for various protocols and services
type: object
properties:
  sync:
    $ref: './SyncConfig.yaml'
  nodes:
    $ref: './NodesConfig.yaml'
  live:
    $ref: './LiveConfig.yaml'
  va:
    $ref: './VoiceAssistantConfig.yaml'
  mqtt:
    $ref: './MqttConfig.yaml'
  hue:
    $ref: './HueConfig.yaml'
  ntp:
    $ref: './NtpConfig.yaml'
required: []
example:
  sync:
    port0: 21324
    port1: 65506
    recv:
      bri: true
      col: true
      fx: true
      grp: 1
      seg: true
      sb: false
    send:
      dir: true
      btn: true
      va: false
      hue: false
      macro: false
      grp: 1
      ret: 2
  nodes:
    list: true
    bcast: true
  live:
    en: true
    mso: false
    port: 5568
    mc: false
    dmx:
      uni: 1
      seqskip: false
      e131prio: 0
      addr: 1
      dss: 0
      mode: 1
    timeout: 25
    maxbri: true
    no-gc: false
    offset: 0
  va:
    alexa: true
    macros: [0, 0]
    p: 1
  mqtt:
    en: false
    broker: ""
    port: 1883
    user: ""
    pskl: 0
    cid: ""
    rtn: true
    topics:
      device: "wled/device"
      group: "wled/all"
  hue:
    en: false
    id: 1
    iv: 10
    recv:
      on: true
      bri: true
      col: true
    ip: [192, 168, 1, 100]
  ntp:
    en: true
    host: "pool.ntp.org"
    tz: 0
    offset: 0
    ampm: false
    ln: 0.0
    lt: 0.0 