description: Interface configuration settings for various protocols and services
type: object
properties:
  sync:
    type: object
    description: WLED sync configuration
    nullable: true
    properties:
      port0:
        type: integer
        format: uint16
        description: WLED notifier default port
        minimum: 0
        maximum: 65535
        nullable: true
      port1:
        type: integer
        format: uint16
        description: WLED notifier supplemental port
        minimum: 0
        maximum: 65535
        nullable: true
      recv:
        type: object
        description: WLED notifier receive configuration
        nullable: true
        properties:
          bri:
            type: boolean
            description: Apply brightness from incoming notifications
            nullable: true
          col:
            type: boolean
            description: Apply color
            nullable: true
          fx:
            type: boolean
            description: Apply effects setup
            nullable: true
          grp:
            type: integer
            format: uint8
            description: Sync receive groups this instance belongs to (bit mapped)
            minimum: 0
            maximum: 255
            nullable: true
          seg:
            type: boolean
            description: Apply segment options
            nullable: true
          sb:
            type: boolean
            description: Apply segment bounds (start, stop, offset)
            nullable: true
      send:
        type: object
        description: WLED notifier send configuration
        nullable: true
        properties:
          dir:
            type: boolean
            description: Send notification if change via UI or HTTP API
            nullable: true
          btn:
            type: boolean
            description: Send if updated by button or infrared remote
            nullable: true
          va:
            type: boolean
            description: Send notification if updated via Alexa
            nullable: true
          hue:
            type: boolean
            description: Send notification if Hue light changes
            nullable: true
          macro:
            type: boolean
            description: Send notification for macro
            nullable: true
          grp:
            type: integer
            format: uint8
            description: Sync groups this instance syncs (bit mapped)
            minimum: 0
            maximum: 255
            nullable: true
          ret:
            type: integer
            format: uint8
            description: Number of times a UDP sync message is retransmitted. Increase to increase reliability
            minimum: 0
            maximum: 255
            nullable: true
  nodes:
    type: object
    description: Node configuration
    nullable: true
    properties:
      list:
        type: boolean
        description: Node List Enabled
        nullable: true
      bcast:
        type: boolean
        description: Node Broadcast Enabled
        nullable: true
  live:
    type: object
    description: Live data configuration
    nullable: true
    properties:
      en:
        type: boolean
        description: Receive UDP realtime
        nullable: true
      mso:
        type: boolean
        description: Use Main Segment Only
        nullable: true
      port:
        type: integer
        format: uint16
        description: DMX in port. E1.31 default is 5568, Art-Net is 6454
        minimum: 0
        maximum: 65535
        nullable: true
      mc:
        type: boolean
        description: Multicast or unicast mode
        nullable: true
      dmx:
        type: object
        description: DMX configuration
        nullable: true
        properties:
          uni:
            type: integer
            format: uint16
            description: Settings for E1.31 (sACN) protocol (only DMX_MODE_MULTIPLE_* can span over consecutive universes)
            minimum: 0
            maximum: 65535
            nullable: true
          seqskip:
            type: boolean
            description: Freeze instead of flickering
            nullable: true
          e131prio:
            type: integer
            format: uint8
            description: E1.31 port priority (if != 0 priority handling is active)
            minimum: 0
            maximum: 255
            nullable: true
          addr:
            type: integer
            format: uint16
            description: DMX start address of fixture, a.k.a. first Channel [for E1.31 (sACN) protocol]
            minimum: 0
            maximum: 65535
            nullable: true
          dss:
            type: integer
            format: uint16
            description: DMX channel spacing; Number of void/unused channels between each segments DMX channels
            minimum: 0
            maximum: 65535
            nullable: true
          mode:
            type: integer
            format: uint8
            description: DMX mode
            enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
            x-enumNames:
              - DMX_MODE_DISABLED
              - DMX_MODE_SINGLE_RGB
              - DMX_MODE_SINGLE_DRGB
              - DMX_MODE_EFFECT
              - DMX_MODE_MULTIPLE_RGB
              - DMX_MODE_MULTIPLE_DRGB
              - DMX_MODE_MULTIPLE_RGBW
              - DMX_MODE_EFFECT_W
              - DMX_MODE_EFFECT_SEGMENT
              - DMX_MODE_EFFECT_SEGMENT_W
              - DMX_MODE_PRESET
              - RSVD1
              - RSVD2
              - RSVD3
              - RSVD4
              - RSVD5
              - RSVD6
            nullable: true
      timeout:
        type: integer
        format: uint16
        description: (ms timeout of realtime mode before returning to normal mode) / 100
        minimum: 0
        maximum: 65535
        nullable: true
      maxbri:
        type: boolean
        description: Enable to force max brightness if source has very dark colors that would be black
        nullable: true
      no-gc:
        type: boolean
        description: Disable gamma correction; activate if gamma correction is handled by the source
        nullable: true
      offset:
        type: integer
        format: uint32
        description: Realtime LED offset
        minimum: 0
        maximum: 4294967295
        nullable: true
  va:
    type: object
    description: Voice Assistant configuration
    nullable: true
    properties:
      alexa:
        type: boolean
        description: Enable device discovery by Amazon Echo
        nullable: true
      macros:
        type: array
        description: Alexa macros [macroAlexaOn, macroAlexaOff]
        minItems: 2
        maxItems: 2
        items:
          type: integer
          format: uint8
          minimum: 0
          maximum: 255
        nullable: true
      p:
        type: integer
        format: uint8
        description: Number of presets to expose to Alexa, starting from preset 1, up to 9
        minimum: 0
        maximum: 255
        nullable: true
  mqtt:
    type: object
    description: MQTT configuration
    nullable: true
    properties:
      en:
        type: boolean
        description: MQTT enabled
        nullable: true
      broker:
        type: string
        description: Both domains and IPs should work (no SSL)
        nullable: true
      port:
        type: integer
        format: uint16
        description: MQTT port
        minimum: 0
        maximum: 65535
        nullable: true
      user:
        type: string
        description: Optional username for MQTT auth
        nullable: true
      pskl:
        type: integer
        format: uint8
        description: Optional length of password for MQTT auth
        minimum: 0
        maximum: 255
        nullable: true
      cid:
        type: string
        description: Override the client ID
        nullable: true
      rtn:
        type: boolean
        description: Retain brightness and color
        nullable: true
      topics:
        type: object
        description: MQTT topics configuration
        nullable: true
        properties:
          device:
            type: string
            description: Main MQTT topic (individual per device, default is wled/mac)
            nullable: true
          group:
            type: string
            description: Second MQTT topic (for example to group devices)
            nullable: true
  hue:
    type: object
    description: Philips Hue configuration
    nullable: true
    properties:
      en:
        type: boolean
        description: Poll hue bridge for light state
        nullable: true
      id:
        type: integer
        format: uint8
        description: ID of hue lamp to sync to. Find the ID in the hue app ("about" section)
        minimum: 0
        maximum: 255
        nullable: true
      iv:
        type: integer
        format: uint16
        description: (low values (< 1sec) may cause lag but offer quicker response) / 100
        minimum: 0
        maximum: 65535
        nullable: true
      recv:
        type: object
        description: Hue receiver configuration
        nullable: true
        properties:
          on:
            type: boolean
            description: Hue Apply On Off
            nullable: true
          bri:
            type: boolean
            description: Hue Apply Bri
            nullable: true
          col:
            type: boolean
            description: Hue Apply Color
            nullable: true
      ip:
        type: array
        description: Hue bridge IP address
        minItems: 4
        maxItems: 4
        items:
          type: integer
          format: uint8
          minimum: 0
          maximum: 255
        nullable: true
  ntp:
    type: object
    description: NTP configuration
    nullable: true
    properties:
      en:
        type: boolean
        description: Get internet time. Only required if you use clock overlays or time-activated macros
        nullable: true
      host:
        type: string
        description: NTP server to use
        nullable: true
      tz:
        type: integer
        format: uint8
        description: Timezone ID. Refer to timezones array in wled10_ntp.ino
        enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 255]
        x-enumNames:
          - TZ_UTC
          - TZ_UK
          - TZ_EUROPE_CENTRAL
          - TZ_EUROPE_EASTERN
          - TZ_US_EASTERN
          - TZ_US_CENTRAL
          - TZ_US_MOUNTAIN
          - TZ_US_ARIZONA
          - TZ_US_PACIFIC
          - TZ_CHINA
          - TZ_JAPAN
          - TZ_AUSTRALIA_EASTERN
          - TZ_NEW_ZEALAND
          - TZ_NORTH_KOREA
          - TZ_INDIA
          - TZ_SASKACHEWAN
          - TZ_AUSTRALIA_NORTHERN
          - TZ_AUSTRALIA_SOUTHERN
          - TZ_HAWAII
          - TZ_NOVOSIBIRSK
          - TZ_ANCHORAGE
          - TZ_MX_CENTRAL
          - TZ_PAKISTAN
          - TZ_RSVD1
          - TZ_RSVD2
          - TZ_RSVD3
          - TZ_RSVD4
          - TZ_RSVD5
          - TZ_RSVD6
          - TZ_INIT
        nullable: true
      offset:
        type: integer
        format: uint32
        description: Seconds to offset from UTC before timezone calculation
        minimum: 0
        maximum: 4294967295
        nullable: true
      ampm:
        type: boolean
        description: Use AM/PM; 12h/24h clock format
        nullable: true
      ln:
        type: number
        format: double
        description: Longitude
        nullable: true
      lt:
        type: number
        format: double
        description: Latitude
        nullable: true
required: []
example:
  sync:
    port0: 21324
    port1: 65506
    recv:
      bri: true
      col: true
      fx: true
      grp: 1
      seg: true
      sb: false
    send:
      dir: true
      btn: true
      va: false
      hue: false
      macro: false
      grp: 1
      ret: 2
  nodes:
    list: true
    bcast: true
  live:
    en: true
    mso: false
    port: 5568
    mc: false
    dmx:
      uni: 1
      seqskip: false
      e131prio: 0
      addr: 1
      dss: 0
      mode: 1
    timeout: 25
    maxbri: true
    no-gc: false
    offset: 0
  va:
    alexa: true
    macros: [0, 0]
    p: 1
  mqtt:
    en: false
    broker: ""
    port: 1883
    user: ""
    pskl: 0
    cid: ""
    rtn: true
    topics:
      device: "wled/device"
      group: "wled/all"
  hue:
    en: false
    id: 1
    iv: 10
    recv:
      on: true
      bri: true
      col: true
    ip: [192, 168, 1, 100]
  ntp:
    en: true
    host: "pool.ntp.org"
    tz: 0
    offset: 0
    ampm: false
    ln: 0.0
    lt: 0.0 