description: Light configuration settings
type: object
properties:
  scale-bri:
    type: integer
    format: uint8
    description: Percentage of brightness to set (to limit power, if you set it to 50 and set bri to 255, actual brightness will be 127)
    minimum: 0
    maximum: 255
    nullable: true
  pal-mode:
    type: integer
    format: uint8
    description: "paletteBlend: 0 - wrap when moving, 1 - always wrap, 2 - never wrap, 3 - none (undefined)"
    minimum: 0
    maximum: 255
    nullable: true
  aseg:
    type: boolean
    description: >
      If true, a segment per bus will be created on boot and LED settings save.
      If false, only one segment spanning the total LEDs is created,
      but not on LED settings save if there is more than one segment currently
    nullable: true
  gc:
    $ref: './GammaCorrection.yaml'
  tr:
    $ref: './TransitionConfig.yaml'
  nl:
    $ref: './NightlightConfig.yaml'
required: []
example:
  scale-bri: 100
  pal-mode: 0
  aseg: false
  gc:
    bri: 1.0
    col: 1.0
    val: 1.0
  tr:
    dur: 7
    pal: false
    rpc: 60
  nl:
    mode: 0
    dur: 60
    tbri: 0
    macro: 0 