description: Network configuration settings
type: object
properties:
  ins:
    type: array
    description: Network interface configurations (WLED source only uses one element)
    nullable: true
    items:
      $ref: './NetworkInstance.yaml'
required: []
example:
  ins:
    - ssid: "MyWiFiNetwork"
      pskl: 12
      ip: [192, 168, 1, 100]
      gw: [192, 168, 1, 1]
      sn: [255, 255, 255, 0] 