type: object
description: >
  Nightlight mode configuration that controls automatic dimming and color changes
  over a specified duration. Useful for creating gradual fade-outs or sunrise/sunset effects.
properties:
  mode:
    type: integer
    format: uint8
    minimum: 0
    maximum: 3
    description: >
      Nightlight operation mode:
      * 0 (NL_MODE_SET) - After nightlight time elapsed, set to target brightness immediately
      * 1 (NL_MODE_FADE) - Fade to target brightness gradually over the duration
      * 2 (NL_MODE_COLORFADE) - Fade to target brightness and secondary color gradually over the duration
      * 3 (NL_MODE_SUN) - Sunrise/sunset simulation. Target brightness is set immediately,
        then Sunrise effect starts. Maximum duration is 60 minutes.
    example: 1
  dur:
    type: integer
    format: uint8
    minimum: 0
    maximum: 255
    description: >
      Duration of the nightlight mode in minutes. For sunrise/sunset mode (3),
      maximum duration is 60 minutes. A value of 0 disables the nightlight feature.
    example: 60
  tbri:
    type: integer
    format: uint8
    minimum: 0
    maximum: 255
    description: >
      Target brightness level to reach after nightlight duration completes.
      This is the final brightness that will be set or faded to.
      For sunrise/sunset mode (3), this determines if it's a sunrise (non-zero) or sunset (zero).
    example: 0
  macro:
    type: integer
    format: uint8
    minimum: 0
    maximum: 255
    description: >
      Macro to execute after the nightlight duration completes and the target
      brightness is reached. The macro is executed after the transition is complete.
      A value of 0 means no macro will be executed.
    example: 0
example:
  mode: 1
  dur: 60
  tbri: 0
  macro: 0 