type: object
description: Over-The-Air (OTA) update configuration
example: {}
properties:
  lock:
    type: boolean
    description: Prevents OTA firmware updates without password. ALWAYS enable if system exposed to any public networks
    nullable: true
  lock-wifi:
    type: boolean
    description: Prevents access to WiFi settings when OTA lock is enabled
    nullable: true
  pskl:
    type: integer
    format: uint8
    minimum: 0
    maximum: 255
    description: Length of OTA password
    nullable: true
  aota:
    type: boolean
    description: ArduinoOTA allows easy updates directly from the IDE. Careful, it does not auto-disable when OTA lock is on
    nullable: true 