type: object
description: Remote control configuration
example: {}
properties:
  remote_enabled:
    type: boolean
    description: Whether remote control is enabled
    nullable: true
  linked_remotes:
    type: array
    description: Array of MAC addresses for linked remote devices
    items:
      type: string
      description: MAC address of a linked remote device
      pattern: '^[0-9a-fA-F]{12}$'
    nullable: true
  espnow_enabled:
    type: boolean
    description: Whether ESP-NOW wireless technology is enabled for remote control
    nullable: true
  espnow_sync:
    type: boolean
    description: Whether to use ESP-NOW for synchronization between devices
    nullable: true 