description: Timer and countdown configuration
type: object
properties:
  cntdwn:
    description: Countdown configuration
    type: object
    nullable: true
    properties:
      goal:
        description: The time that the countdown is counting down towards as an array of [year, month, day, hour, minute, second]
        type: array
        minItems: 6
        maxItems: 6
        items:
            type: integer
            format: uint8
            minimum: 0
            maximum: 255
        example: [24, 12, 31, 23, 59, 59]
      macro:
        type: integer
        format: uint8
        minimum: 0
        maximum: 255
        description: Macro to execute when countdown reaches goal
        nullable: true
  ins:
    description: Array of timer instances
    type: array
    nullable: true
    items:
      type: object
      properties:
        en:
          type: boolean
          description: Whether the timer instance is enabled
          nullable: true
        hour:
          type: integer
          format: uint8
          minimum: 0
          maximum: 255
          description: Hour when the timer triggers
          nullable: true
        min:
          type: integer
          format: int8
          minimum: -128
          maximum: 127
          description: Minute when the timer triggers
          nullable: true
        macro:
          type: integer
          format: uint8
          minimum: 0
          maximum: 255
          description: Macro to execute when triggered
          nullable: true
        start:
          description: Day and month that this timer turns on every year
          type: object
          nullable: true
          properties:
            mon:
              type: integer
              format: uint8
              minimum: 0
              maximum: 15
              description: The month (4-bit value)
              nullable: true
            day:
              type: integer
              format: uint8
              minimum: 0
              maximum: 255
              description: The day of the month
              nullable: true
        end:
          description: Day and month that this timer turns off every year
          type: object
          nullable: true
          properties:
            mon:
              type: integer
              format: uint8
              minimum: 0
              maximum: 15
              description: The month (4-bit value)
              nullable: true
            day:
              type: integer
              format: uint8
              minimum: 0
              maximum: 255
              description: The day of the month
              nullable: true
example:
  cntdwn:
    goal: [24, 12, 31, 23, 59, 59]
    macro: 1
  ins:
    - en: true
      hour: 20
      min: 30
      macro: 2
      start:
        mon: 1
        day: 1
      end:
        mon: 12
        day: 31 